version: '3'

services:
  # 内部監視用
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring_resources/prometheus:/etc/prometheus
    environment:
      - TZ="Asia/Tokyo"
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9900:9900"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - TZ="Asia/Tokyo"
    volumes:
      - ./monitoring_resources/grafana/dashboards:/val/lib/grafana/dashboards
      - ./monitoring_resources/grafana/datasource.yaml:/etc/grafana/datasources/datasource.yaml
    ports:
      - "3000:3000"
  
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    environment:
      - TZ="Asia/Tokyo"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    environment:
      - TZ="Asia/Tokyo"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
  
  