version: '3'

services:
  ## 既存のDBを使用する場合は以下をコメントアウト
  mysql:
    container_name: jawiki_db
    build:
      context: ./mysql/
      dockerfile: build/Dockerfile
    env_file: mysql.env
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data/:/var/lib/mysql
    ports:
      - 3306:3306
    # 文字コードを触ったりファイルを読み込むおまじない②を書いています
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --local-infile=1
  ## コメントアウトここまで
  ## このファイルの最後のvolumesもコメントアウトしてください

  elasticsearch01:
    container_name: ls_es01
    build: 
      context: ./elasticsearch/
      dockerfile: build/Dockerfile
    environment:
      # - node.name=es01
      # - cluster.name=es-docker-cluster
      # - cluster.initial_master_nodes=es01
      # - discovery.seed_hosts=ls_es02, ls_es03
      #- node.master=true
      #- node.data=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - TZ=Asia/Tokyo
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging: 
      driver: 'json-file'
      options: 
        max-size: '10m'
        max-file: '3'
    ports: 
      - "9200:9200"
    depends_on:
      - mysql
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  logstash:
    container_name: logstash
    build: 
      context: ./logstash/
      dockerfile: build/Dockerfile
    ports: 
      - "9600:9600"
    env_file: mysql.env
    environment:
      - TZ=Asia/Tokyo
    depends_on: 
      - elasticsearch01
      # - elasticsearch02
      # - elasticsearch03
      - mysql
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/config/:/usr/share/logstash/config/
      - ./logstash/index_template/:/index_template/


## 既存のDBを使用する場合は以下をコメントアウト
volumes:
  mysql_data: