global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9900"
  - job_name: "elasticsearch"
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets:
          - "elasticsearch:9200"
  - job_name: "resources"
    static_configs:
      - targets: ["cadvisor:8080", "node-exporter:9100"]